# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5464864471102ff6b125369c1d0fcd652672e0799534b00911fb1c8240c5f5976448c3ca19e7443fa0956ac64395bb3c4faddacf17799228b8bcc8097ddaeca0

test:
  secret_key_base: 3c0a1891cc9e698c36814c40dd7acdba7f660ef432056c51488fdaf80685c533eca57518a7e9abaa7b374cae252df2762f6fa932f3ee7d208059f8326d8a48fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
